<a href="https://colab.research.google.com/github/sanath-02/web-dev-notes/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.Series([0.25,0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index


RangeIndex(start=0, stop=4, step=1)

In [ ]:
data[2]

0.75

In [ ]:
data[0]

0.25

In [ ]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [ ]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['d']

1.0

In [ ]:
data['b':'d']

b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [ ]:
pd.Series({6:'f', 1:'b', 8:'e'})

6    f
1    b
8    e
dtype: object

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
states=pd.DataFrame({'pop':population,'city':area})
states

pop    city
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [ ]:
states['California':'Florida']

pop    city
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area=pd.Series(area_dict)
states=pd.DataFrame({'pop':population,'city':area})
states.loc[['California','New York'],:]

pop    city
California  38332521  423967
New York    19651127  141297

In [ ]:
states.pop

<bound method DataFrame.pop of                  pop    city
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995>

In [ ]:
states['California':'Florida']

pop    city
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312

In [ ]:
area_dict = {'California': [1,2,4,5], 'Texas': [4,2,2,1], 'New York': [1,2,4,5],
             'Florida': [1,2,4,5], 'Illinois': [1,2,4,5]}
bh=pd.DataFrame(area_dict)
bh

California  Texas  New York  Florida  Illinois
0           1      4         1        1         1
1           2      2         2        2         2
2           4      2         4        4         4
3           5      1         5        5         5

In [ ]:
data = [{'a': i, 'b': i*4}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  4
2  2  8

In [ ]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
dattu=pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])
dattu

foo       bar
a  0.140957  0.921068
b  0.224177  0.821965
c  0.008718  0.552113

In [ ]:
dattu['a':'c']

foo       bar
a  0.140957  0.921068
b  0.224177  0.821965
c  0.008718  0.552113

In [ ]:
arr_1=np.array(([1,2,3,4],[5,6,7,8]));
print(arr_1.shape)
print(arr_1)
arr_1=np.array([1,2,3,4,5,6,7,8,9,10,11,12]);
arr_2=arr_1.reshape(2,3,2);
print(arr_2.shape)
print(arr_2)


(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
l=[19,65,57,39,152,639,121,44,90,190]
final_list=list(filter(lambda n:((n%13)==0 or(n%19)==0),l))
print(final_list)

[19, 65, 57, 39, 152, 190]


In [ ]:
from functools import reduce
l=[19,65,57,39,152,639,121,44,90,190]
sum=0
for i in l:
  sum=sum+i
print(sum)
final_list=reduce(lambda x,y:x+y,l)
print(final_list)

24276441302592336000
24276441302592336000


In [ ]:
my_list=list(("CSE","DSE","AIML"))
A_tuple=("ECE",)
my_list.extend(A_tuple)
print(my_list)
my_list.pop(1)
print(my_list)

['CSE', 'DSE', 'AIML', 'ECE']
['CSE', 'AIML', 'ECE']


In [ ]:
a = "Ramaiah University"
print(a[::-1])

ytisrevinU haiamaR


In [ ]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
B = [[6, 9, 4], 
    [-3, 7, 2]]
result=[[0,0,0],[0,0,0]]
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
for r in result:
    print(r)


[-6, 37, 12]
[-54, 11, -4]


In [1]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array.shape)

(2, 3)
